name: 'Kiwi build'
description: 'Build using kiwi'

inputs:
  image-directory:
    required: True
  target-directory:
    required: True
    default: /tmp
  repository:
    required: True
    default: https://download.opensuse.org/distribution/leap/15.6/repo/oss
  extra_repositories:
    required: True
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        _kiwi_file=(${image_dir}/*.kiwi)
        # for now we just hope that for multiple kiwi files the first one is what we want
        _image_version=`xmllint --xpath 'string(//version)' ${_kiwi_file}`
        _image_name=`xmllint --xpath 'string(//image/@name)' ${_kiwi_file}`
        _container_tag=`xmllint --xpath 'string(//containerconfig/@tag)' ${_kiwi_file}`
        _container_name=`xmllint --xpath 'string(//containerconfig/@name)' ${_kiwi_file}`
        sudo kiwi-ng system build --description ${_image_name} \
          --set-repo ${repository} `for r in $extra_repos; do echo -n " --add-repo $r "; done` \
          --target-dir ${target_dir}/${_image_name}
        podman load -i ${target_dir}/${_image_name}/${_image_name}.x86_64-${_image_version}.docker.tar
        podman push ${_container_name}:${_container_tag}
        podman push ${_container_name}:${_container_tag} ${_container_name}:latest
      shell: bash
      env:
        image_dir: ${{inputs.image-directory}}
        target_dir: ${{inputs.target-directory}}
        repository: ${{inputs.repository}}
        extra_repos: ${{inputs.extra_repositories}}
