name: Build and deploy containers

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  leap-base:
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build base image for leap
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: leap-base
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/distribution/leap/15.6/repo/non-oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/non-oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/backports
            https://mirror.aardsoft.fi/opensuse//update/leap/15.6/sle
            https://download.opensuse.org/repositories/Virtualization:/containers/15.6

  tw-base:
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build base image for tumbleweed
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: tumbleweed-base
          repository: https://mirror.aardsoft.fi/opensuse///tumbleweed/repo/oss
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/non-oss

  leap-derived:
    needs:
      - leap-base
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build dev-leap image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: dev-leap
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/distribution/leap/15.6/repo/non-oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/non-oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/backports
            https://mirror.aardsoft.fi/opensuse//update/leap/15.6/sle
            https://download.opensuse.org/repositories/Virtualization:/containers/15.6

  tw-derived-base:
    needs:
      - tw-base
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build wayland base image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: wayland-base
          repository: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/non-oss

  tw-derived:
    needs:
      - tw-base
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build tw dev image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: dev-tumbleweed
          repository: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss
          kiwi-extra-args: --debug
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/non-oss
            http://download.opensuse.org/repositories/CrossToolchain:/avr/openSUSE_Tumbleweed/
            http://download.opensuse.org/repositories/devel:/gcc/openSUSE_Factory/
            https://download.opensuse.org/repositories/devel:/languages:/ruby:/extensions/openSUSE_Tumbleweed/
            http://download.opensuse.org//repositories//home:/bhwachter/openSUSE_Tumbleweed
            https://packages.microsoft.com/opensuse/15/prod
            https://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Tumbleweed/

  tw-derived-base-derived:
    needs:
      - tw-derived-base
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build firefox image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: tw-wayland/firefox
          repository: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/non-oss
            https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/

      - name: Build krita image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: tw-wayland/krita
          repository: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/non-oss

      - name: Build wireshark image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: tw-wayland/wireshark
          repository: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/non-oss

      - name: Build chromium image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: tw-wayland/chromium
          repository: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/non-oss
            https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/

      - name: Build google-chrome image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: tw-wayland/google-chrome
          repository: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss
          extra-repositories: |
            http://dl.google.com/linux/chrome/rpm/stable/x86_64
            https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/non-oss
            https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/

#          - name: Build derived image
#            uses: ./kiwi-build
#            with:
#              image-directory: test-image-docker-derived
#              repository: https://download.opensuse.org/tumbleweed/repo/oss/
#              source-image: tumbleweed-base
#          - name: 'Build images'
#            run: |
#              sudo kiwi-ng system build --description dev-leap \
#              --set-repo https://download.opensuse.org/distribution/leap/15.6/repo/oss \
#              --add-repo https://download.opensuse.org/repositories/Virtualization:/containers/15.6 \
#              --target-dir /tmp/dev-leap
#              _ver=`xmllint --xpath 'string(//version)' dev-leap/appliance.kiwi`
#              _tag=`xmllint --xpath 'string(//containerconfig/@tag)' dev-leap/appliance.kiwi`
#              _name=`xmllint --xpath 'string(//containerconfig/@name)' dev-leap/appliance.kiwi`
#              podman load -i /tmp/dev-leap/dev-leap.x86_64-${_ver}.docker.tar
#              podman push ${_name}:${_tag}
#              #docker build suse_leap_dev --tag ghcr.io/aard-fi/suse_leap_dev:latest
#              #docker push ghcr.io/aard-fi/suse_leap_dev:latest
